export const icons = {
    add: "/add.png",
    disk: "/disk.png",
    document: "/document.png",
    download: "/download.png",
    file: "/file.png",
    folder: "/folder.png",
    home: "/home.png",
    menu: "/menu.png",
    music: "/music.png",
    picture: "/picture.png",
    recent: "/recent.png",
    search: "/search.png",
    star: "/star.png",
    trash: "/trash.png",
    video: "/video.png",
};
